[project]
name = "bitcoin-savings-dapp"
version = "1.0.0"
description = "Bitcoin-backed recurring savings plan on Stacks"
telemetry = true
cache_dir = "./.clarinet/cache"
requirements = []
boot_contracts = []

[contracts.recurring-savings]
path = "contracts/recurring-savings.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = true